spring.application.name=seafood-store
server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SeafoodStoreDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true